# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0003_remove_announcement_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
